### PR TITLE
Fix reading/getting env vars

### PR DESCRIPTION
**Pull request by nlemoine**
putenv/getenv is not thread safe: https://jolicode.com/blog/what-you-need-to-know-about-environment-variables-with-php#thread-safety-of-getenv

### CODE REVIEW

**Comment by voronkovich** [comment]
@nlemoine, I think we should keep `getenv()` as a fallback, because `$_ENV` could be disabled with [variables_order](https://www.php.net/manual/en/ini.core.php#ini.variables-order) directive:

```ini
; php.ini
variables_order = "GPCS"
```

```php
$value = $_ENV[$key] ?? getenv($key);
```

**Comment by voronkovich** [comment]
I just checked an official [php.ini-production](https://github.com/php/php-src/blob/201c691fab036b40f8b2ddcfd253fd21089ed799/php.ini-production#L652). The `$_ENV` is disabled by default. So I think it's better to use `$_SERVER` variable instead.

**Comment by nlemoine** [comment]
Hello @voronkovich, 

Thanks you for the prompt feedback!

> I just checked an official [php.ini-production](https://github.com/php/php-src/blob/201c691fab036b40f8b2ddcfd253fd21089ed799/php.ini-production#L652).

Interesting! However, [`$_ENV` is still widely used](https://github.com/search?q=%22%24_ENV%22+language%3APHP+&type=code) and I think I never stumble on a server with E disabled.

Dotenv libraries usually [populate both `$_SERVER` and `$_ENV`](https://github.com/symfony/dotenv/blob/a26be30fd61678dab694a18a85084cea7673bbf3/Dotenv.php#L185-L208).

I updated the code to read from: `$_SERVER`, `$_ENV`, `getenv`, in that order:

```php
$value = $_SERVER[$key] ?? $_ENV[$key] ?? getenv($key) !== false ?: null;
```
Checking if `E` is disabled with `ini_get('variable_order')` seems overkill IMHO.

Let me know if this looks right to you.

**Comment by voronkovich** [comment]
@nlemoine, thanks for the contribution!

**Comment by nlemoine** [comment]
Thanks for considering it!

**Pull request merged**
